# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-02 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_thumb',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='image',
            name='image_web',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
