# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-22 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.CharField(max_length=50),
        ),
    ]
