# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-22 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageModel',
            new_name='Image',
        ),
    ]
