# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-02 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170302_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_thumb',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_web',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
