# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-13 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170302_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_thumb',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_web',
        ),
        migrations.AddField(
            model_name='image',
            name='url_thumb',
            field=models.CharField(default='/django/media/thumb/', max_length=256),
        ),
        migrations.AddField(
            model_name='image',
            name='url_web',
            field=models.CharField(default='/django/media/web/', max_length=256),
        ),
    ]
