# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-13 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170313_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url_thumb',
            field=models.CharField(default='/media/thumb/', max_length=256),
        ),
        migrations.AlterField(
            model_name='image',
            name='url_web',
            field=models.CharField(default='/media/web/', max_length=256),
        ),
    ]
