# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-22 14:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170222_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='date_taken',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 22, 14, 32, 34, 127699, tzinfo=utc)),
        ),
    ]
