# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-22 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170222_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date_taken',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
