# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-13 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170313_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='date_taken',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
