# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-14 01:06
from __future__ import unicode_literals

from django.db import migrations, models
import fg.api.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170313_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_prod',
            field=models.ImageField(upload_to=fg.api.helpers.path_and_rename),
        ),
        migrations.AlterField(
            model_name='image',
            name='url_thumb',
            field=models.CharField(default='/media/thumb/default.jpg', max_length=256),
        ),
        migrations.AlterField(
            model_name='image',
            name='url_web',
            field=models.CharField(default='/media/web/default.jpg', max_length=256),
        ),
    ]
