# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-18 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170318_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_thumb',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_web',
        ),
    ]
