# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-18 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20170318_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='album',
        ),
        migrations.RemoveField(
            model_name='image',
            name='category',
        ),
        migrations.RemoveField(
            model_name='image',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='image',
            name='date_taken',
        ),
        migrations.RemoveField(
            model_name='image',
            name='media',
        ),
        migrations.RemoveField(
            model_name='image',
            name='place',
        ),
        migrations.RemoveField(
            model_name='image',
            name='tag',
        ),
        migrations.AlterField(
            model_name='image',
            name='image_thumb',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_web',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
