# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-18 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import fg.api.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20170318_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_prod',
            field=models.ImageField(upload_to=fg.api.helpers.path_and_rename),
        ),
    ]
