# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-18 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20170318_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_thumb',
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(default='default.jpg', editable=False, upload_to=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_web',
            field=models.ImageField(default='default.jpg', editable=False, upload_to=''),
        ),
    ]
