# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-18 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20170318_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
