# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-19 21:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20170319_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='image_prod',
            new_name='prod',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='image_web',
            new_name='web',
        ),
    ]
