# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-20 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20170319_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='thumbnail',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='web',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
