# DEPRECATED
# FROM alexsuch/angular-cli:1.1.0
# ENV HOME=/home/app

# # Copy only package.json in order to cache the npm install
# COPY package.json $HOME/angular_frontend/
# RUN cd $HOME/angular_frontend && npm install

# # Then copy the rest of the folders
# COPY . $HOME/angular_frontend/

# # Now set the working directory
# WORKDIR $HOME/angular_frontend



