FROM node:7

RUN npm install -g @angular/cli@1.0.0-beta.31 && npm cache clean

RUN useradd --user-group --create-home --shell /bin/false app
ENV HOME=/home/app

COPY package.json $HOME/angular/
RUN chown -R app:app $HOME/*

USER app
WORKDIR $HOME/angular
RUN npm install &&\
	npm cache clean

CMD ["ng", "build", "--watch"]
